name       : cfitsio
version    : 3.47
release    : 2
source     :
    - http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio-3.47.tar.gz : 418516f10ee1e0f1b520926eeca6b77ce639bed88804c7c545e74f26b3edf4ef
license    : MIT
component  : programming.library
summary    : CFITSIO is a library of ANSI C routines for reading and writing FITS format data files.
description: |
    CFITSIO is a library of ANSI C routines for reading and writing FITS format data files. 
builddeps  :
    - pkgconfig(krb5)
    - pkgconfig(libcurl)
    - pkgconfig(libnghttp2)
    - pkgconfig(libssh2)
setup      : |
    %configure --enable-reentrant
build      : |
    %make shared
install    : |
    %make_install
    rm -f $installdir/usr/lib64/*.a
