name       : cfitsio
version    : '3.48'
release    : 3
source     :
    - http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio-3.48.tar.gz : 91b48ffef544eb8ea3908543052331072c99bf09ceb139cb3c6977fc3e47aac1
license    : MIT
component  : programming.library
summary    : CFITSIO is a library of ANSI C routines for reading and writing FITS format data files.
description: |
    CFITSIO is a library of ANSI C routines for reading and writing FITS format data files.
builddeps  :
    - pkgconfig(libcurl)
setup      : |
    %configure --enable-reentrant
build      : |
    %make shared
install    : |
    %make_install
    rm -f $installdir/usr/lib64/*.a
